after-login-command = []
after-startup-command = []
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
automatically-unhide-macos-hidden-apps = false
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = "move-mouse window-lazy-center"

[key-mapping]
    preset = 'qwerty'

[key-mapping.key-notation-to-key-code]
    "/" = "minus"
    "." = "period"
    "," = "comma"
    "=" = "backtick"

[gaps]
    inner.horizontal = 10  
    inner.vertical =   10  
    outer.left =       10  
    outer.bottom =     10 
    outer.top =        10 
    outer.right =      10

[mode.main.binding]
    alt-esc = ['mode active']

[mode.active.binding]
    alt-esc = ['mode main']

    alt-h = ['focus left']
    alt-j = ['focus down']
    alt-k = ['focus up']
    alt-l = ['focus right']

    alt-shift-h = ['move left']
    alt-shift-j = ['move down']
    alt-shift-k = ['move up']
    alt-shift-l = ['move right']

    alt-a = ['layout accordion horizontal vertical']
    alt-t = ['layout tiling', 'layout tiles horizontal vertical']
    alt-f = ['layout floating']

    alt-space = ['fullscreen']

    ctrl-h = ['join-with left']
    ctrl-j = ['join-with down']
    ctrl-k = ['join-with up']
    ctrl-l = ['join-with right']

    alt-i = ['resize smart +50']
    alt-shift-i = ['resize smart -50']

    alt-1 = ['workspace 1']
    alt-2 = ['workspace 2']
    alt-3 = ['workspace 3']
    alt-4 = ['workspace 4']

    alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
    alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
    alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
    alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4']

    alt-tab = 'workspace-back-and-forth'

    alt-s = 'mode service'

[mode.service.binding]
    alt-r = ['reload-config', 'mode main']
    alt-l = ['flatten-workspace-tree', 'mode main'] # reset layout

[[on-window-detected]]
    check-further-callbacks = true
    if.workspace = '1'
    run = 'layout floating'
