# Applications
bind = SUPER, RETURN, exec, ghostty
bind = SUPER, SPACE, exec, fuzzel

# Windows
bind = SUPER, Q, killactive
bind = SUPER, F, fullscreen, 0
bind = SUPER SHIFT, V, togglefloating

# Session
bind = SUPER SHIFT, Q, exit
bind = SUPER, L, exec, hyprlock

# Workspaces
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5

# Clipboard
bind = SUPER, V, exec, cliphist list | fuzzel --dmenu | cliphist decode | wl-copy

# Screenshots
bind = , PRINT, exec, mkdir -p ~/Pictures && grim ~/Pictures/screenshot-$(date +'%Y-%m-%d_%H-%M-%S').png
bind = SHIFT, PRINT, exec, mkdir -p ~/Pictures && grim -g "$(slurp)" ~/Pictures/screenshot-$(date +'%Y-%m-%d_%H-%M-%S').png
