unbind r
bind r source-file ~/.config/tmux/tmux.conf
 
set -g prefix C-s
 
set -g mouse on
 
# set-option -g xterm-keys on
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set-option -g status-position top
set-option -g status-justify centre
set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Options to make tmux more pleasant
set -g default-terminal "tmux-256color"

# modern
set -as terminal-features ",xterm-ghostty:RGB"
set -as terminal-features ",ghostty:RGB"
set -as terminal-features ",xterm-256color:RGB"

# fallback für ältere Setups
set -as terminal-overrides ",xterm-ghostty:Tc"
set -as terminal-overrides ",ghostty:Tc"
set -as terminal-overrides ",xterm-256color:Tc"
set -g cursor-style block

set -g base-index 1
setw -g pane-base-index 1
  
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "" 

set -g status-style bg=default
set -g status-left-style bg=default
set -g status-right-style bg=default

set -g window-status-style bg=default
set -g window-status-current-style bg=default

# set clipboard for ssh
set -g set-clipboard on
set -g allow-passthrough on

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
