# outsourced the config files
[ -s "$HOME/dotfiles/zsh/autocomplete" ] && \. "$HOME/dotfiles/zsh/autocomplete" # load the autocomplete 
[ -s "$HOME/dotfiles/zsh/myalias" ] && \. "$HOME/dotfiles/zsh/myalias" # load my aliases
[ -s "$HOME/dotfiles/zsh/prompt" ] && \. "$HOME/dotfiles/zsh/prompt" # load the layout of the prompt
[ -s "$HOME/dotfiles/zsh/nvm_bash_completion" ] && \. "$HOME/dotfiles/zsh/nvm_bash_completion" #load nvm bash completion

